// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_resumes_parse_resume_file = {
    file: (Blob | File);
};

export type Body_soe_import_soe_data = {
    file: (Blob | File);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type JobApplicationCreate = {
    /**
     * 公司名称
     */
    company_name: string;
    /**
     * 公告链接
     */
    announcement_url?: (string | null);
    /**
     * 投递链接
     */
    apply_url?: (string | null);
    /**
     * 行业
     */
    industry?: (string | null);
    /**
     * 标签
     */
    tags?: (string | null);
    /**
     * 批次
     */
    batch?: (string | null);
    /**
     * 职位
     */
    position?: (string | null);
    /**
     * 地点
     */
    location?: (string | null);
    /**
     * 投递截止时间
     */
    deadline?: (string | null);
};

export type JobApplicationPublic = {
    /**
     * 公司名称
     */
    company_name: string;
    /**
     * 公告链接
     */
    announcement_url?: (string | null);
    /**
     * 投递链接
     */
    apply_url?: (string | null);
    /**
     * 行业
     */
    industry?: (string | null);
    /**
     * 标签
     */
    tags?: (string | null);
    /**
     * 批次
     */
    batch?: (string | null);
    /**
     * 职位
     */
    position?: (string | null);
    /**
     * 地点
     */
    location?: (string | null);
    /**
     * 投递截止时间
     */
    deadline?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type JobApplicationsPublic = {
    data: Array<JobApplicationPublic>;
    count: number;
};

export type JobApplicationUpdate = {
    company_name?: (string | null);
    announcement_url?: (string | null);
    apply_url?: (string | null);
    industry?: (string | null);
    tags?: (string | null);
    batch?: (string | null);
    position?: (string | null);
    location?: (string | null);
    deadline?: (string | null);
};

export type JobConfig = {
    days?: number;
    hours?: number;
    cron_hour?: number;
    type?: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RecruitmentAnnouncementCreate = {
    /**
     * 公告标题
     */
    title: string;
    /**
     * 公告链接
     */
    url: string;
    /**
     * 发布日期
     */
    publish_date?: (string | null);
    /**
     * 来源
     */
    source?: (string | null);
    /**
     * 分类
     */
    category?: (string | null);
};

export type RecruitmentAnnouncementPublic = {
    /**
     * 公告标题
     */
    title: string;
    /**
     * 公告链接
     */
    url: string;
    /**
     * 发布日期
     */
    publish_date?: (string | null);
    /**
     * 来源
     */
    source?: (string | null);
    /**
     * 分类
     */
    category?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type RecruitmentAnnouncementsPublic = {
    data: Array<RecruitmentAnnouncementPublic>;
    count: number;
};

export type RecruitmentAnnouncementUpdate = {
    title?: (string | null);
    url?: (string | null);
    publish_date?: (string | null);
    source?: (string | null);
    category?: (string | null);
};

export type RegulatoryUnitCreate = {
    /**
     * 监管单位名称
     */
    name: string;
    /**
     * 简介
     */
    description?: (string | null);
    /**
     * Deepseek锐评
     */
    deepseek_comment?: (string | null);
    /**
     * 级别
     */
    level?: (string | null);
};

export type RegulatoryUnitPublic = {
    /**
     * 监管单位名称
     */
    name: string;
    /**
     * 简介
     */
    description?: (string | null);
    /**
     * Deepseek锐评
     */
    deepseek_comment?: (string | null);
    /**
     * 级别
     */
    level?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type RegulatoryUnitsPublic = {
    data: Array<RegulatoryUnitPublic>;
    count: number;
};

export type RegulatoryUnitUpdate = {
    name?: (string | null);
    description?: (string | null);
    deepseek_comment?: (string | null);
    level?: (string | null);
};

export type ResumeCreate = {
    title: string;
    /**
     * Markdown content
     */
    content?: (string | null);
};

export type ResumePublic = {
    title: string;
    /**
     * Markdown content
     */
    content?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type ResumesPublic = {
    data: Array<ResumePublic>;
    count: number;
};

export type ResumeUpdate = {
    title?: (string | null);
    content?: (string | null);
};

export type SoeEnterpriseCreate = {
    /**
     * 企业名称
     */
    name: string;
    /**
     * 官网链接
     */
    website?: (string | null);
    /**
     * 企业简介
     */
    description?: (string | null);
    /**
     * Deepseek锐评
     */
    deepseek_comment?: (string | null);
    /**
     * 行业分类
     */
    category?: (string | null);
    /**
     * 所属监管单位ID
     */
    regulatory_unit_id: string;
};

export type SoeEnterprisePublic = {
    /**
     * 企业名称
     */
    name: string;
    /**
     * 官网链接
     */
    website?: (string | null);
    /**
     * 企业简介
     */
    description?: (string | null);
    /**
     * Deepseek锐评
     */
    deepseek_comment?: (string | null);
    /**
     * 行业分类
     */
    category?: (string | null);
    /**
     * 所属监管单位ID
     */
    regulatory_unit_id: string;
    id: string;
    created_at: string;
    updated_at: string;
    regulatory_unit_name?: (string | null);
};

export type SoeEnterprisesPublic = {
    data: Array<SoeEnterprisePublic>;
    count: number;
};

export type SoeEnterpriseUpdate = {
    name?: (string | null);
    website?: (string | null);
    description?: (string | null);
    deepseek_comment?: (string | null);
    category?: (string | null);
    regulatory_unit_id?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AnnouncementsReadAnnouncementsData = {
    category?: (string | null);
    limit?: number;
    skip?: number;
    source?: (string | null);
};

export type AnnouncementsReadAnnouncementsResponse = (RecruitmentAnnouncementsPublic);

export type AnnouncementsCreateAnnouncementData = {
    requestBody: RecruitmentAnnouncementCreate;
};

export type AnnouncementsCreateAnnouncementResponse = (RecruitmentAnnouncementPublic);

export type AnnouncementsReadAnnouncementData = {
    id: string;
};

export type AnnouncementsReadAnnouncementResponse = (RecruitmentAnnouncementPublic);

export type AnnouncementsUpdateAnnouncementData = {
    id: string;
    requestBody: RecruitmentAnnouncementUpdate;
};

export type AnnouncementsUpdateAnnouncementResponse = (RecruitmentAnnouncementPublic);

export type AnnouncementsDeleteAnnouncementData = {
    id: string;
};

export type AnnouncementsDeleteAnnouncementResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type JobApplicationsReadJobApplicationsData = {
    limit?: number;
    skip?: number;
};

export type JobApplicationsReadJobApplicationsResponse = (JobApplicationsPublic);

export type JobApplicationsCreateJobApplicationData = {
    requestBody: JobApplicationCreate;
};

export type JobApplicationsCreateJobApplicationResponse = (JobApplicationPublic);

export type JobApplicationsReadJobApplicationData = {
    id: string;
};

export type JobApplicationsReadJobApplicationResponse = (JobApplicationPublic);

export type JobApplicationsUpdateJobApplicationData = {
    id: string;
    requestBody: JobApplicationUpdate;
};

export type JobApplicationsUpdateJobApplicationResponse = (JobApplicationPublic);

export type JobApplicationsDeleteJobApplicationData = {
    id: string;
};

export type JobApplicationsDeleteJobApplicationResponse = (Message);

export type JobApplicationsInitMockDataResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ResumesReadResumesData = {
    limit?: number;
    skip?: number;
};

export type ResumesReadResumesResponse = (ResumesPublic);

export type ResumesCreateResumeData = {
    requestBody: ResumeCreate;
};

export type ResumesCreateResumeResponse = (ResumePublic);

export type ResumesReadResumeData = {
    id: string;
};

export type ResumesReadResumeResponse = (ResumePublic);

export type ResumesUpdateResumeData = {
    id: string;
    requestBody: ResumeUpdate;
};

export type ResumesUpdateResumeResponse = (ResumePublic);

export type ResumesDeleteResumeData = {
    id: string;
};

export type ResumesDeleteResumeResponse = (Message);

export type ResumesParseResumeFileData = {
    formData: Body_resumes_parse_resume_file;
};

export type ResumesParseResumeFileResponse = (Message);

export type SchedulerRunNowData = {
    days?: number;
};

export type SchedulerRunNowResponse = (unknown);

export type SchedulerConfigureScheduleData = {
    requestBody: JobConfig;
};

export type SchedulerConfigureScheduleResponse = (unknown);

export type SchedulerGetStatusResponse = (unknown);

export type SoeReadRegulatoryUnitsData = {
    limit?: number;
    skip?: number;
};

export type SoeReadRegulatoryUnitsResponse = (RegulatoryUnitsPublic);

export type SoeCreateRegulatoryUnitData = {
    requestBody: RegulatoryUnitCreate;
};

export type SoeCreateRegulatoryUnitResponse = (RegulatoryUnitPublic);

export type SoeReadRegulatoryUnitData = {
    id: string;
};

export type SoeReadRegulatoryUnitResponse = (RegulatoryUnitPublic);

export type SoeUpdateRegulatoryUnitData = {
    id: string;
    requestBody: RegulatoryUnitUpdate;
};

export type SoeUpdateRegulatoryUnitResponse = (RegulatoryUnitPublic);

export type SoeDeleteRegulatoryUnitData = {
    id: string;
};

export type SoeDeleteRegulatoryUnitResponse = (Message);

export type SoeReadEnterprisesData = {
    category?: (string | null);
    limit?: number;
    regulatoryUnitId?: (string | null);
    skip?: number;
};

export type SoeReadEnterprisesResponse = (SoeEnterprisesPublic);

export type SoeCreateEnterpriseData = {
    requestBody: SoeEnterpriseCreate;
};

export type SoeCreateEnterpriseResponse = (SoeEnterprisePublic);

export type SoeReadEnterpriseData = {
    id: string;
};

export type SoeReadEnterpriseResponse = (SoeEnterprisePublic);

export type SoeUpdateEnterpriseData = {
    id: string;
    requestBody: SoeEnterpriseUpdate;
};

export type SoeUpdateEnterpriseResponse = (SoeEnterprisePublic);

export type SoeDeleteEnterpriseData = {
    id: string;
};

export type SoeDeleteEnterpriseResponse = (Message);

export type SoeImportSoeDataData = {
    formData: Body_soe_import_soe_data;
};

export type SoeImportSoeDataResponse = (Message);

export type SoeGetSoeImportTemplateResponse = (unknown);

export type SoeGetEnterpriseCategoriesResponse = (Array<(string)>);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);