"""add_job_application_table

Revision ID: 230073704a5f
Revises: 1942609fbed0
Create Date: 2025-12-15 01:38:37.812510

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '230073704a5f'
down_revision = '1942609fbed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobapplication',
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('announcement_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('apply_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('batch', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobapplication')
    # ### end Alembic commands ###
