"""Add order field to UserJobApplication

Revision ID: 34ea0ab157a7
Revises: f82ed4b683dc
Create Date: 2025-12-24 17:04:26.072961

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '34ea0ab157a7'
down_revision = 'f82ed4b683dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userjobapplication', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userjobapplication', 'order')
    # ### end Alembic commands ###
