"""Add deepseek_comment to RegulatoryUnit

Revision ID: 5efbdbfd1de6
Revises: b18633d96dfb
Create Date: 2025-12-16 00:21:12.456245

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5efbdbfd1de6'
down_revision = 'b18633d96dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulatoryunit', sa.Column('deepseek_comment', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulatoryunit', 'deepseek_comment')
    # ### end Alembic commands ###
