"""Add target_role to Resume model

Revision ID: 7d0a907b663e
Revises: a002de1c72b6
Create Date: 2025-12-23 17:21:03.064882

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7d0a907b663e'
down_revision = 'a002de1c72b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('target_role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'target_role')
    # ### end Alembic commands ###
