"""Add original_content and optimized_content to Resume

Revision ID: a002de1c72b6
Revises: ca50bde0a7ba
Create Date: 2025-12-17 01:07:38.545668

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a002de1c72b6'
down_revision = 'ca50bde0a7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('original_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('resume', sa.Column('optimized_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'optimized_content')
    op.drop_column('resume', 'original_content')
    # ### end Alembic commands ###
