"""Add RecruitmentAnnouncement

Revision ID: b01d88810939
Revises: 230073704a5f
Create Date: 2025-12-15 15:14:49.766390

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b01d88810939'
down_revision = '230073704a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruitmentannouncement',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('publish_date', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruitmentannouncement')
    # ### end Alembic commands ###
