"""Add deepseek_comment to SoeEnterprise

Revision ID: b18633d96dfb
Revises: 5b047855279b
Create Date: 2025-12-15 23:09:08.953015

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b18633d96dfb'
down_revision = '5b047855279b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soeenterprise', sa.Column('deepseek_comment', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soeenterprise', 'deepseek_comment')
    # ### end Alembic commands ###
