"""Add target_jd to Resume model

Revision ID: c4996047164a
Revises: 7d0a907b663e
Create Date: 2025-12-24 09:50:42.759341

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c4996047164a'
down_revision = '7d0a907b663e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('target_jd', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'target_jd')
    # ### end Alembic commands ###
