"""Add Resume tables

Revision ID: ca50bde0a7ba
Revises: 77e38071c8a9
Create Date: 2025-12-17 00:13:51.775694

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ca50bde0a7ba'
down_revision = '77e38071c8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('resume_user_id_fkey'), 'resume', type_='foreignkey')
    op.create_foreign_key(None, 'resume', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('resume', 'original_filename')
    op.drop_column('resume', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('resume', sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.create_foreign_key(op.f('resume_user_id_fkey'), 'resume', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('resume', 'owner_id')
    # ### end Alembic commands ###
