"""Add UserJobApplication model

Revision ID: f82ed4b683dc
Revises: c4996047164a
Create Date: 2025-12-24 16:44:24.360763

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f82ed4b683dc'
down_revision = 'c4996047164a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userjobapplication',
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('apply_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('progress', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('referral_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('apply_url2', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('apply_url3', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userjobapplication')
    # ### end Alembic commands ###
