/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSoeRouteImport } from './routes/_layout/soe'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutJobApplicationsRouteImport } from './routes/_layout/job-applications'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAnnouncementsRouteImport } from './routes/_layout/announcements'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutResumesRouteRouteImport } from './routes/_layout/resumes/route'
import { Route as LayoutResumesIndexRouteImport } from './routes/_layout/resumes/index'
import { Route as LayoutResumesResumeIdRouteImport } from './routes/_layout/resumes/$resumeId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSoeRoute = LayoutSoeRouteImport.update({
  id: '/soe',
  path: '/soe',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJobApplicationsRoute = LayoutJobApplicationsRouteImport.update({
  id: '/job-applications',
  path: '/job-applications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnnouncementsRoute = LayoutAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResumesRouteRoute = LayoutResumesRouteRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResumesIndexRoute = LayoutResumesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutResumesRouteRoute,
} as any)
const LayoutResumesResumeIdRoute = LayoutResumesResumeIdRouteImport.update({
  id: '/$resumeId',
  path: '/$resumeId',
  getParentRoute: () => LayoutResumesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/resumes': typeof LayoutResumesRouteRouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/announcements': typeof LayoutAnnouncementsRoute
  '/items': typeof LayoutItemsRoute
  '/job-applications': typeof LayoutJobApplicationsRoute
  '/settings': typeof LayoutSettingsRoute
  '/soe': typeof LayoutSoeRoute
  '/': typeof LayoutIndexRoute
  '/resumes/$resumeId': typeof LayoutResumesResumeIdRoute
  '/resumes/': typeof LayoutResumesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/announcements': typeof LayoutAnnouncementsRoute
  '/items': typeof LayoutItemsRoute
  '/job-applications': typeof LayoutJobApplicationsRoute
  '/settings': typeof LayoutSettingsRoute
  '/soe': typeof LayoutSoeRoute
  '/': typeof LayoutIndexRoute
  '/resumes/$resumeId': typeof LayoutResumesResumeIdRoute
  '/resumes': typeof LayoutResumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/resumes': typeof LayoutResumesRouteRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/announcements': typeof LayoutAnnouncementsRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/job-applications': typeof LayoutJobApplicationsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/soe': typeof LayoutSoeRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/resumes/$resumeId': typeof LayoutResumesResumeIdRoute
  '/_layout/resumes/': typeof LayoutResumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/resumes'
    | '/admin'
    | '/announcements'
    | '/items'
    | '/job-applications'
    | '/settings'
    | '/soe'
    | '/'
    | '/resumes/$resumeId'
    | '/resumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/announcements'
    | '/items'
    | '/job-applications'
    | '/settings'
    | '/soe'
    | '/'
    | '/resumes/$resumeId'
    | '/resumes'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/resumes'
    | '/_layout/admin'
    | '/_layout/announcements'
    | '/_layout/items'
    | '/_layout/job-applications'
    | '/_layout/settings'
    | '/_layout/soe'
    | '/_layout/'
    | '/_layout/resumes/$resumeId'
    | '/_layout/resumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/soe': {
      id: '/_layout/soe'
      path: '/soe'
      fullPath: '/soe'
      preLoaderRoute: typeof LayoutSoeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/job-applications': {
      id: '/_layout/job-applications'
      path: '/job-applications'
      fullPath: '/job-applications'
      preLoaderRoute: typeof LayoutJobApplicationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/announcements': {
      id: '/_layout/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof LayoutAnnouncementsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resumes': {
      id: '/_layout/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof LayoutResumesRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resumes/': {
      id: '/_layout/resumes/'
      path: '/'
      fullPath: '/resumes/'
      preLoaderRoute: typeof LayoutResumesIndexRouteImport
      parentRoute: typeof LayoutResumesRouteRoute
    }
    '/_layout/resumes/$resumeId': {
      id: '/_layout/resumes/$resumeId'
      path: '/$resumeId'
      fullPath: '/resumes/$resumeId'
      preLoaderRoute: typeof LayoutResumesResumeIdRouteImport
      parentRoute: typeof LayoutResumesRouteRoute
    }
  }
}

interface LayoutResumesRouteRouteChildren {
  LayoutResumesResumeIdRoute: typeof LayoutResumesResumeIdRoute
  LayoutResumesIndexRoute: typeof LayoutResumesIndexRoute
}

const LayoutResumesRouteRouteChildren: LayoutResumesRouteRouteChildren = {
  LayoutResumesResumeIdRoute: LayoutResumesResumeIdRoute,
  LayoutResumesIndexRoute: LayoutResumesIndexRoute,
}

const LayoutResumesRouteRouteWithChildren =
  LayoutResumesRouteRoute._addFileChildren(LayoutResumesRouteRouteChildren)

interface LayoutRouteChildren {
  LayoutResumesRouteRoute: typeof LayoutResumesRouteRouteWithChildren
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAnnouncementsRoute: typeof LayoutAnnouncementsRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutJobApplicationsRoute: typeof LayoutJobApplicationsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSoeRoute: typeof LayoutSoeRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutResumesRouteRoute: LayoutResumesRouteRouteWithChildren,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAnnouncementsRoute: LayoutAnnouncementsRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutJobApplicationsRoute: LayoutJobApplicationsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSoeRoute: LayoutSoeRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
